### ISSUE TITLE
[Vector] Add 'number of vectors' param to the vector component

### ISSUE THREAD

**Issue by LennyLip** [physics-is-beautiful/pib-eval-library#10]

**Comment by LennyLip** [comment]
It is better to add the number of vectors to [VectorDataIO](https://github.com/studyhub-co/components-library/blob/master/src/components/vector/IData/index.ts#L12) JSON data interface. In this case, we can store the number of vectors that are required in selected material dynamically across the materials data. E.g. teacher entered 2 vectors in the answer field in edit data mode - the student can draw 2 vectors max only. 
Leave it for later.

**Comment by nscozzaro** [comment]
We also need to make sure the vector a student draws does not get snapped
to the center. It should stay where it's drawn, like in production

**Comment by LennyLip** [comment]
>We also need to make sure the vector a student draws does not get snapped
to the center.

**Comment by LennyLip** [comment]
> We also need to make sure the vector a student draws does not get snapped to the center.
 
Yes, I see.  The problem is that we have JSON data field now and store data with [typescript interface](https://github.com/studyhub-co/components-library/blob/master/src/components/vector/IData/vector.ts) requirements. We use [io-ts ](https://github.com/gcanti/io-ts/blob/master/index.md) to able get dynamic JSON data interfaces - as for typescript code, and as for JSON data (from/to server) run-time validation. 

So, the process now looks like in old version teacher mode (the server-side store is [React reducer](https://github.com/studyhub-co/components-library/blob/master/src/components/vector/reducer.tsx#L66) really): 
1) draw vector 
2) save vector on the server-side.
3) get data from the server-side.
4) to draw vector based on this data.

The problem is that the server-side (and the JSON data and reducer data, in accordance with interface) does not store the start point of the vector. So we don't know how to draw the vector according to [JSON schema/interface](https://github.com/studyhub-co/components-library/blob/master/src/components/vector/IData/vector.ts). 

It seems we need to store the start point of the vector somehow.

**Comment by LennyLip** [comment]
fixed with restricting updating vectors on canvas from the redux store (for student view). not elegant, but the fastest solution.
