### ISSUE TITLE
[Vector] add "clear vectors" button for student view

### ISSUE THREAD

**Issue by LennyLip** [physics-is-beautiful/pib-eval-library#7]
![clear](https://user-images.githubusercontent.com/955994/130435981-e6034d36-ef4c-43f0-b15d-7c4cb3467e20.png)

**Comment by LennyLip** [comment]
Reset vectors canvas if we try to draw a new vector with a number more than ['the number of vectors'.](https://github.com/studyhub-co/components-library/issues/10)

**Comment by nscozzaro** [comment]
We don't need a clear vectors button.
We need to not prevent drawing multiple vectors.
Displaying multiple vectors is required.
